### ISSUE TITLE
Failed to activate the open-project-in-tower package

### ISSUE THREAD

**Issue by asux** [jwohlfeil/atom-open-project-in-tower#12]
1. Open project with repo added in Tower.
2. Press ⌃⌥R.

**Atom Version**: 0.206.0
**System**: Mac OS X 10.10.3
**Thrown From**: [open-project-in-tower](https://github.com/jwohlfeil/atom-open-project-in-tower) package, v1.1.0
### Stack Trace

Failed to activate the open-project-in-tower package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/asux/Яндекс.Диск/Applications/Atom/packages/open-project-in-tower/lib/open-project-in-tower.coffee:7:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:770:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:219:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
  9x -0:35.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:02.6.0 open-project-in-tower:open (div.settings-view.pane-item)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "deprecation-cop",
      "minimap",
      "open-in-sourcetree",
      "fancy-new-file",
      "atom-lint",
      "atom-terminal-panel",
      "file-icon-supplement",
      "file-type-icons",
      "pdf-view",
      "editor-settings",
      "circle-ci",
      "tree-view-finder",
      "git-control"
    ],
    "projectHome": "~/Projects"
  }
}
```
### Installed Packages

``` coffee
# User
api-blueprint-preview, v0.5.1
atom-alignment, v0.12.1
atom-ctags, v4.1.1
autocomplete-paths, v1.0.2
autocomplete-ruby, v0.1.0
color-picker, v2.0.4
cucumber, v0.5.0
editorconfig, v1.0.0
ember-cli-helper, v0.7.2
file-icons, v1.5.7
git-projects, v1.14.1
highlight-selected, v0.9.3
language-api-blueprint, v1.0.1
language-docker, v1.1.3
language-ember-htmlbars, v0.3.0
language-ember-script, v0.2.0
language-emblem, v0.2.0
language-hosts, v0.1.2
language-slim, v0.4.0
linter, v0.12.6
linter-csslint, v0.0.13
linter-jsonlint, v0.1.4
linter-pylint, v0.2.2
linter-rubocop, v0.2.7
linter-scss-lint, v1.0.4
local-history, v3.2.2
open-project-in-tower, v1.1.0
project-manager, v1.15.8
regex-railroad-diagram, v0.7.4
rspec-snippets, v0.4.0
ruby-block, v0.3.3
wercker-status, v1.0.5

# Dev
No dev packages
```

**Comment by asux** [comment]
This error no longer occurs git version. Please, release it to Atom packages https://atom.io/packages/open-project-in-tower.
